{% set data = load_setup_py_data() %}

package:
  name: q2cli
  version: {{ data.get('version') }}

source:
  path: ../..

build:
  script: python setup.py install
  entry_points:
    - qiime=q2cli.__main__:qiime

requirements:
  build:
    - python 3.5*
    - setuptools
    - pip
    - click
    - qiime2 2017.3.*

  run:
    - python 3.5*
    - setuptools
    - pip
    - click
    - qiime2 2017.3.*

test:
  imports:
    - q2cli

  commands:
    - QIIMETEST= qiime --help

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
